
import "./styles/globals.scss";
import 'bootstrap/dist/css/bootstrap.css'
import '@fortawesome/fontawesome-free/css/all.css'
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import { UserProvider } from "./providers/userProvider";




export const metadata = {
  title: "Dit hjem",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
   

        {children}

        <Footer/>
        </UserProvider>
        </body>
    </html>
  );
}
